name: farm

channels:
  - defaults

dependencies:
  - python=3.8
  - pip
  - git
  - anaconda::numpy
  - numba::llvmlite
  - scipy
  - click
  - pyyaml
  - cffi
  - astropy
  - h5py
  - gsl
  - jupyter
  - matplotlib
  - pandas
  - toml
  - conda-forge::reproject
  - pip:
    - git+https://github.com/SimonP2207/tools21cm.git
    - git+https://github.com/SimonP2207/ARatmospy
    - git+https://github.com/telegraphic/pygdsm
    - git+https://github.com/SimonP2207/ARatmospy
    - git+https://github.com/OxfordSKA/OSKAR.git@master#egg=oskarpy&subdirectory=python
    - git+https://github.com/21cmFAST/21cmFAST.git
    - casatools==6.5.2.26
    - casatasks==6.5.2.26
    - casaplotms==1.8.7
    - casaviewer==1.6.6
    - casampi==0.5.01
    - casashell==6.5.2.26
    - casadata==2022.9.5
    - casaplotserver==1.4.6
    - almatasks==1.5.2
    - casatestutils==6.5.2.26
